/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Component for Isometric Office 3D Model
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function IsometricOffice(props) {
  const { nodes, materials, scene } = useGLTF(
    '/src/assets/models/isometric_office/scene.gltf'
  );

  return (
    <group {...props} dispose={null}>
      <primitive object={scene} />
    </group>
  );
}

// Preload the model for better performance
useGLTF.preload('/src/assets/models/isometric_office/scene.gltf');

export default IsometricOffice;
